-- Poseu el codi dels procediments/funcions emmagatzemats, triggers, ..., usats al projecte

--Primer el que hem de fer es fer la taula per Truck

CREATE TABLE trucks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR2(100) NOT NULL,
    horsepower NUMBER NOT NULL,
    kilometers NUMBER NOT NULL,
    hasTrailer NUMBER(1) NOT NULL,
    engineType VARCHAR2(50) NOT NULL
);

--PL/SQL

    -- 1. Procedura per insertar
    CREATE OR REPLACE PROCEDURE insert_truck(
        p_brand IN VARCHAR2,
        p_horsepower IN NUMBER,
        p_kilometers IN NUMBER,
        p_hasTrailer IN NUMBER,
        p_engineType IN VARCHAR2
    ) IS
    BEGIN
        INSERT INTO trucks (brand, horsepower, kilometers, hasTrailer, engineType)
        VALUES (p_brand, p_horsepower, p_kilometers, p_hasTrailer, p_engineType);
    END;


    -- 2. Procedura per modificar
    CREATE OR REPLACE PROCEDURE update_truck(
        p_id IN NUMBER,
        p_brand IN VARCHAR2,
        p_horsepower IN NUMBER,
        p_kilometers IN NUMBER,
        p_hasTrailer IN NUMBER,
        p_engineType IN VARCHAR2
    ) IS
    BEGIN
        UPDATE trucks
        SET brand = p_brand,
            horsepower = p_horsepower,
            kilometers = p_kilometers,
            hasTrailer = p_hasTrailer,
            engineType = p_engineType
        WHERE id = p_id;
    END;

    

    -- 3. Procedura per borrar
    CREATE OR REPLACE PROCEDURE delete_truck(
        p_id IN NUMBER
    ) IS
    BEGIN
        DELETE FROM trucks
        WHERE id = p_id;
    END;


    