-- Poseu el codi dels procediments/funcions emmagatzemats, triggers, ..., usats al projecte

--Primer el que hem de fer es fer la taula per Truck

CREATE TABLE TRUCK (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BRAND VARCHAR2(100) NOT NULL,
    HORSEPOWER NUMBER NOT NULL,
    KILOMETERS NUMBER NOT NULL,
    IS_ELECTRIC CHAR(1) CHECK (IS_ELECTRIC IN ('Y', 'N')) NOT NULL
);

--PL/SQL

    -- 1. Procedura per insertar
    CREATE OR REPLACE PROCEDURE INSERT_TRUCK(
        P_BRAND IN TRUCK.BRAND%TYPE,
        P_HORSEPOWER IN TRUCK.HORSEPOWER%TYPE,
        P_KILOMETERS IN TRUCK.KILOMETERS%TYPE,
        P_IS_ELECTRIC IN TRUCK.IS_ELECTRIC%TYPE
    ) IS
    BEGIN
        INSERT INTO TRUCK (
            BRAND,
            HORSEPOWER,
            KILOMETERS,
            IS_ELECTRIC
        ) VALUES (
            P_BRAND,
            P_HORSEPOWER,
            P_KILOMETERS,
            P_IS_ELECTRIC
        );
    END;
    

    -- 2. Procedura per modificar
    CREATE OR REPLACE PROCEDURE MODIFY_TRUCK(
        P_ID IN TRUCK.ID%TYPE,
        P_BRAND IN TRUCK.BRAND%TYPE,
        P_HORSEPOWER IN TRUCK.HORSEPOWER%TYPE,
        P_KILOMETERS IN TRUCK.KILOMETERS%TYPE,
        P_IS_ELECTRIC IN TRUCK.IS_ELECTRIC%TYPE
    ) IS
    BEGIN
        UPDATE TRUCK
        SET
            BRAND = P_BRAND,
            HORSEPOWER = P_HORSEPOWER,
            KILOMETERS = P_KILOMETERS,
            IS_ELECTRIC = P_IS_ELECTRIC
        WHERE
            ID = P_ID;
    END;
    

    -- 3. Procedura per borrar
    CREATE OR REPLACE PROCEDURE DELETE_TRUCK(
        P_ID IN TRUCK.ID%TYPE
    ) IS
    BEGIN
        DELETE FROM TRUCK
        WHERE
            ID = P_ID;
    END;
    

    -- 4. Procedura per guardar
    CREATE OR REPLACE PROCEDURE SAVE_TRUCK(
        P_ID IN TRUCK.ID%TYPE,
        P_BRAND IN TRUCK.BRAND%TYPE,
        P_HORSEPOWER IN TRUCK.HORSEPOWER%TYPE,
        P_KILOMETERS IN TRUCK.KILOMETERS%TYPE,
        P_IS_ELECTRIC IN TRUCK.IS_ELECTRIC%TYPE
    ) IS
        V_COUNT INTEGER;
    BEGIN
        SELECT
            COUNT(*) INTO V_COUNT
        FROM
            TRUCK
        WHERE
            ID = P_ID;
        IF V_COUNT = 0 THEN
            INSERT INTO TRUCK (
                BRAND,
                HORSEPOWER,
                KILOMETERS,
                IS_ELECTRIC
            ) VALUES (
                P_BRAND,
                P_HORSEPOWER,
                P_KILOMETERS,
                P_IS_ELECTRIC
            );
        ELSE
            UPDATE TRUCK
            SET
                BRAND = P_BRAND,
                HORSEPOWER = P_HORSEPOWER,
                KILOMETERS = P_KILOMETERS,
                IS_ELECTRIC = P_IS_ELECTRIC
            WHERE
                ID = P_ID;
        END IF;
    END;
    